CREATE TABLE SOCIAL_MEDIA (
                ID NUMERIC(10,0) IDENTITY(1,1) NOT NULL,
                DT_DELETE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
				NAME VARCHAR(50) NOT NULL,
                CONSTRAINT PK_SOCIAL_MEDIA PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_SOCIAL_MEDIA ON SOCIAL_MEDIA(NAME);
CREATE INDEX IX_SOCIAL_MEDIA_ID ON SOCIAL_MEDIA(ID);