CREATE TABLE USER_SECURITY (
                ID NUMERIC(10,0) IDENTITY(1,1) NOT NULL,
                DT_DELETE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                USER VARCHAR(50) NOT NULL,
                PASSWORD VARCHAR(100) NOT NULL,
                CONSTRAINT PK_USER_SECURITY PRIMARY KEY (ID)
);
	CREATE UNIQUE INDEX UK_USER_SECURITY ON USER_SECURITY(USER);
	CREATE INDEX IX_USER_SECURITY_ID ON USER_SECURITY(ID);