CREATE TABLE PHONE (
                ID NUMERIC(10,0) IDENTITY(1,1) NOT NULL,
                DT_DELETE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
				NUMBER NUMERIC(10,0) NOT NULL,
                COUNTRY_CODE NUMERIC(3,0) NOT NULL,
                REGION_CODE NUMERIC(3,0) NOT NULL,
                CONSTRAINT PK_PHONE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_PHONE ON PHONE( NUMBER, COUNTRY_CODE, REGION_CODE );
CREATE INDEX IX_PHONE_ID ON PHONE(ID);