ID
CREATE TABLE USER_SECURITY (
                ID VARCHAR(5) NOT NULL,
                DT_DELETE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                USER VARCHAR(50) NOT NULL,
                PASSWORD VARCHAR(100) NOT NULL,
                CONSTRAINT IDX_USER_SECURITY PRIMARY KEY (ID)
);


CREATE TABLE SOCIAL_MEDIA (
                ID NUMERIC(5) NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                NAME VARCHAR(50) NOT NULL,
                CONSTRAINT IDX_SOCIAL_MEDIA PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX UK_SOCIAL_MEDIA
 ON SOCIAL_MEDIA
 ( NAME );

CREATE TABLE PERSON_SOCIAL_MEDIA (
                ID NUMERIC(5) NOT NULL,
                DT_DELETE TIMESTAMP,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                ID_SOCIAL_MEDIA NUMERIC(5) NOT NULL,
                ID_USER_SECURITY VARCHAR(5) NOT NULL,
                CONSTRAINT IDX_PERSON_SOCIAL_MEDIA PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX UK_PERSON_SOCIAL_MEDIA
 ON PERSON_SOCIAL_MEDIA
 ( ID_SOCIAL_MEDIA, ID_USER_SECURITY );

CREATE TABLE ADRESS (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                NAME VARCHAR(100) NOT NULL,
                REFERENCE VARCHAR(100) NOT NULL,
                COMPLEMENT VARCHAR(150),
                DISTRICT VARCHAR(100) NOT NULL,
                TOWN VARCHAR(100) NOT NULL,
                COUNTRY VARCHAR(100) NOT NULL,
                POST_CODE VARCHAR(25) NOT NULL,
                CONSTRAINT IDX_ADRESS PRIMARY KEY (ID)
);


CREATE TABLE PHONE (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                NUMBER NUMERIC(10) NOT NULL,
                COUNTRY_CODE NUMERIC(3) NOT NULL,
                REGION_CODE NUMERIC(3) NOT NULL,
                CONSTRAINT IDX_PHONE PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX PHONES_UK
 ON PHONE
 ( NUMBER, COUNTRY_CODE, REGION_CODE );

CREATE TABLE GOAL (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP NOT NULL,
                CONSTRAINT IDX_GOAL PRIMARY KEY (ID)
);


CREATE TABLE RESUME_DETAIL (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                CONSTRAINT IDX_RESUME_DETAIL PRIMARY KEY (ID)
);


CREATE TABLE RESUME (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                CONSTRAINT IDX_RESUME PRIMARY KEY (ID)
);


CREATE TABLE PERSON (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                NAME VARCHAR(100) NOT NULL,
                CPF VARCHAR(11) NOT NULL,
                DT_BIRTHDAY DATE NOT NULL,
                CONSTRAINT IDX_PERSON PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX UK_PERSON_CPF
 ON PERSON
 ( CPF );

CREATE TABLE PERSON_DETAIL (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                ID_PERSON NUMERIC(10) NOT NULL,
                ID_PERSON_SOCIAL_MEDIA NUMERIC(5) NOT NULL,
                CONSTRAINT IDX_PERSON_DETAIL PRIMARY KEY (ID)
);


CREATE TABLE PERSON_ADRESS (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                ID_ADRESS NUMERIC(10) NOT NULL,
                ID_PERSON NUMERIC(10) NOT NULL,
                CONSTRAINT IDX_PERSON_ADRESS PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX UK_PERSON_ADRESS
 ON PERSON_ADRESS
 ( ID_ADRESS, ID_PERSON );

CREATE TABLE PERSON_PHONE (
                ID IDENTITY NOT NULL,
                DT_CREATE TIMESTAMP NOT NULL,
                DT_UPDATE TIMESTAMP NOT NULL,
                DT_DELETE TIMESTAMP,
                ID_PHONE NUMERIC(10) NOT NULL,
                ID_PERSON NUMERIC(10) NOT NULL,
                CONSTRAINT IDX_PERSON_PHONE PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX UK_PERSON_PHONE
 ON PERSON_PHONE
 ( ID_PHONE, ID_PERSON );

ALTER TABLE PERSON_SOCIAL_MEDIA ADD CONSTRAINT FK_USER_SECURITY_PERSON_SOCIAL_MEDIA
FOREIGN KEY (ID_USER_SECURITY)
REFERENCES USER_SECURITY (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PERSON_SOCIAL_MEDIA ADD CONSTRAINT FK_SOCIAL_MEDIA_PERSON_SOCIAL_MEDIA
FOREIGN KEY (ID_SOCIAL_MEDIA)
REFERENCES SOCIAL_MEDIA (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PERSON_DETAIL ADD CONSTRAINT FK_PERSON_SOCIAL_MEDIA_PERSON_DETAIL
FOREIGN KEY (ID_PERSON_SOCIAL_MEDIA)
REFERENCES PERSON_SOCIAL_MEDIA (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PERSON_ADRESS ADD CONSTRAINT FK_ADRESS_PERSON_ADRESS
FOREIGN KEY (ID_ADRESS)
REFERENCES ADRESS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PERSON_PHONE ADD CONSTRAINT FK_PHONE_PERSON_PHONE
FOREIGN KEY (ID_PHONE)
REFERENCES PHONE (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PERSON_DETAIL ADD CONSTRAINT FK_PERSON_PERSON_DETAIL
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PERSON_PHONE ADD CONSTRAINT FK_PERSON_DETAIL_PERSON_PHONE
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON_DETAIL (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PERSON_ADRESS ADD CONSTRAINT FK_PERSON_DETAILS_PERSON_ADRESSES
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON_DETAIL (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;